[package]
name = "zudb-cli"
description = "Command-line interface for zu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme = "../../README.md"
keywords = ["database", "graph", "gql", "cli"]
categories = ["command-line-utilities", "database-implementations"]

[[bin]]
name = "zu"
path = "src/main.rs"

[dependencies]
zu.workspace = true
zu-corpus.workspace = true
zu-json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[[bench]]
name = "cli"
harness = false

[[bench]]
name = "editor"
harness = false

[features]
arrow = ["zu/arrow"]

[lints]
workspace = true
