//! Distils a gql-compat report into a tally, and renders a set of tallies
//! into the conformance scoreboard in `docs/gql-conformance.md`.
//!
//! A full report is a megabyte of per-case timings, host details and a
//! wall clock, none of which is the same twice. Checking one in would
//! mean a diff on every run that says nothing, which is the fastest way
//! to teach a reviewer to stop reading a file. So a report goes through
//! `zu conformance --tally` first, which keeps the counts and the
//! provenance and throws away everything that moves on its own. A tally
//! is a few hundred bytes, it is stable across runs on the same code,
//! and a diff on one is always worth reading.
//!
//! The scoreboard is generated from the checked-in tallies rather than
//! from a live run, so the doc can carry engines this repository's CI
//! has no way to stand up. That is a real limit and the page says so on
//! its face: every column is dated and names the machine, because a
//! number measured somewhere else in another month is worth something
//! but not the same thing as the one measured this morning.
//!
//! Both halves read JSON, the full report and the tally alike, because
//! zu-cli carries one hand written parser and no room for a second
//! format. See the `zu-json` crate for why there is no serde here.

use std::process::ExitCode;
use zu_json::{self as json, Json};

/// The five kinds a case can have, in the order the scoreboard prints
/// them. Fixed here rather than taken from the report so a new kind
/// appearing upstream is a visible failure instead of a column that
/// silently goes missing.
const KINDS: [&str; 5] = [
    "mandatory",
    "optional",
    "condition",
    "grammar",
    "performance",
];

/// One engine's counts, everything the scoreboard prints and nothing
/// that changes between two runs of the same code.
struct Tally {
    engine: String,
    version: String,
    tool: String,
    host: String,
    taken: String,
    selector: String,
    cases: u64,
    pass: u64,
    fail: u64,
    skip: u64,
    error: u64,
    /// Per kind, in `KINDS` order: cases, pass, fail, skip, error.
    by_kind: Vec<[u64; 5]>,
    /// ISO features with at least one passing case, and the number of
    /// features the corpus touches at all.
    features_passing: u64,
    features_touched: u64,
    /// Distinct GQLSTATUS values the engine actually produced on a case
    /// that was graded on one.
    conditions_seen: u64,
}

fn u(v: Option<&Json>) -> u64 {
    v.and_then(Json::as_u64).unwrap_or(0)
}

fn s(v: Option<&Json>) -> String {
    v.and_then(Json::as_str).unwrap_or("unknown").to_string()
}

/// Reads a gql-compat report and keeps the parts that are about the
/// engine rather than about the afternoon.
///
/// `taken` is the one field here that does move on its own, and it is
/// kept on purpose: a tally with no date is a number nobody can weigh.
/// It is also the reason a tally is regenerated by a person or a nightly
/// and not by a per-PR job, since a date that changes every commit is
/// the churn this file exists to avoid.
fn distil(report: &Json) -> Result<Tally, String> {
    let engine = report.get("engine").ok_or("report has no engine")?;
    let totals = report.get("totals").ok_or("report has no totals")?;
    let run = report.get("run").ok_or("report has no run")?;
    let host = report.get("host").ok_or("report has no host")?;

    let by_kind_obj = totals.get("by_kind");
    let mut by_kind = Vec::with_capacity(KINDS.len());
    for kind in KINDS {
        let k = by_kind_obj.and_then(|b| b.get(kind));
        by_kind.push([
            u(k.and_then(|k| k.get("cases"))),
            u(k.and_then(|k| k.get("pass"))),
            u(k.and_then(|k| k.get("fail"))),
            u(k.and_then(|k| k.get("skip"))),
            u(k.and_then(|k| k.get("error"))),
        ]);
    }

    // A feature counts as reached when at least one of its cases passed.
    // Cases that passed for a feature the corpus claims but the engine
    // skipped are not reached, which is the whole distinction the
    // headline percentage blurs.
    let mut features_passing = 0;
    let mut features_touched = 0;
    if let Some(Json::Obj(fs)) = report.get("coverage").and_then(|c| c.get("features")) {
        for (_, f) in fs {
            features_touched += 1;
            if u(f.get("pass")) > 0 {
                features_passing += 1;
            }
        }
    }

    // Distinct codes the engine produced, counted off the cases rather
    // than off a summary, because a code the engine emitted once is the
    // evidence that the machinery works at all.
    let mut codes: Vec<&str> = Vec::new();
    if let Some(Json::Arr(cases)) = report.get("cases") {
        for c in cases {
            if let Some(code) = c.get("got_gqlstatus").and_then(Json::as_str)
                && !code.is_empty()
                && !codes.contains(&code)
            {
                codes.push(code);
            }
        }
    }

    Ok(Tally {
        engine: s(engine.get("adapter")),
        version: s(engine.get("version")),
        tool: s(report.get("tool")),
        host: format!(
            "{} {}, {}",
            s(host.get("os")),
            s(host.get("arch")),
            s(host.get("cpu_model"))
        ),
        // Date only. The clock time would change a checked-in file for
        // no reason a reader cares about.
        taken: s(report.get("generated")).chars().take(10).collect(),
        selector: s(run.get("selector")),
        cases: u(totals.get("cases")),
        pass: u(totals.get("pass")),
        fail: u(totals.get("fail")),
        skip: u(totals.get("skip")),
        error: u(totals.get("error")),
        by_kind,
        features_passing,
        features_touched,
        conditions_seen: codes.len() as u64,
    })
}

/// Renders a tally as the JSON that gets checked in.
fn render_tally(t: &Tally) -> String {
    let mut out = String::new();
    out.push_str("{\n");
    push_str_field(&mut out, "engine", &t.engine, true);
    push_str_field(&mut out, "version", &t.version, true);
    push_str_field(&mut out, "tool", &t.tool, true);
    push_str_field(&mut out, "host", &t.host, true);
    push_str_field(&mut out, "taken", &t.taken, true);
    push_str_field(&mut out, "selector", &t.selector, true);
    out.push_str(&format!("  \"cases\": {},\n", t.cases));
    out.push_str(&format!("  \"pass\": {},\n", t.pass));
    out.push_str(&format!("  \"fail\": {},\n", t.fail));
    out.push_str(&format!("  \"skip\": {},\n", t.skip));
    out.push_str(&format!("  \"error\": {},\n", t.error));
    out.push_str(&format!(
        "  \"features_passing\": {},\n",
        t.features_passing
    ));
    out.push_str(&format!(
        "  \"features_touched\": {},\n",
        t.features_touched
    ));
    out.push_str(&format!("  \"conditions_seen\": {},\n", t.conditions_seen));
    out.push_str("  \"by_kind\": {\n");
    for (i, kind) in KINDS.iter().enumerate() {
        let k = &t.by_kind[i];
        let comma = if i + 1 == KINDS.len() { "" } else { "," };
        out.push_str(&format!(
            "    \"{}\": {{\"cases\": {}, \"pass\": {}, \"fail\": {}, \"skip\": {}, \"error\": {}}}{}\n",
            kind, k[0], k[1], k[2], k[3], k[4], comma
        ));
    }
    out.push_str("  }\n}\n");
    out
}

fn push_str_field(out: &mut String, key: &str, value: &str, comma: bool) {
    out.push_str(&format!("  \"{key}\": \""));
    for c in value.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            c => out.push(c),
        }
    }
    out.push('"');
    if comma {
        out.push(',');
    }
    out.push('\n');
}

/// Reads a checked-in tally back.
fn load_tally(text: &str) -> Result<Tally, String> {
    let j = json::parse(text)?;
    let mut by_kind = Vec::with_capacity(KINDS.len());
    for kind in KINDS {
        let k = j.get("by_kind").and_then(|b| b.get(kind));
        by_kind.push([
            u(k.and_then(|k| k.get("cases"))),
            u(k.and_then(|k| k.get("pass"))),
            u(k.and_then(|k| k.get("fail"))),
            u(k.and_then(|k| k.get("skip"))),
            u(k.and_then(|k| k.get("error"))),
        ]);
    }
    Ok(Tally {
        engine: s(j.get("engine")),
        version: s(j.get("version")),
        tool: s(j.get("tool")),
        host: s(j.get("host")),
        taken: s(j.get("taken")),
        selector: s(j.get("selector")),
        cases: u(j.get("cases")),
        pass: u(j.get("pass")),
        fail: u(j.get("fail")),
        skip: u(j.get("skip")),
        error: u(j.get("error")),
        by_kind,
        features_passing: u(j.get("features_passing")),
        features_touched: u(j.get("features_touched")),
        conditions_seen: u(j.get("conditions_seen")),
    })
}

/// A percentage of judged cases, to one decimal place, without floats in
/// the output path.
///
/// Judged means passed or failed. Skips are out of the denominator
/// because a skip is not a wrong answer, and errors are out because a
/// case that never reached the engine did not measure it. Both are
/// printed separately, in full, right next to this number, since a
/// percentage over a denominator the reader cannot see is a number
/// anyone can move by changing what they count.
fn pct(pass: u64, judged: u64) -> String {
    if judged == 0 {
        return "n/a".to_string();
    }
    let tenths = (pass * 1000 + judged / 2) / judged;
    format!("{}.{}%", tenths / 10, tenths % 10)
}

/// Renders the scoreboard page.
fn render_scoreboard(tallies: &[Tally]) -> String {
    let mut out = String::new();
    out.push_str("# GQL conformance\n\n");
    out.push_str(
        "Generated by `zu conformance --scoreboard docs/conformance/*.json`. Do not edit by hand: a test regenerates it and fails on drift.\n\n",
    );
    out.push_str(
        "Every column is a run of the [gql-compat](https://github.com/tamnd/gql-compat) corpus against one engine, distilled to counts by `zu conformance --tally`. The columns are not measured together and are not meant to be read as a race. They are dated and they name the machine because a number taken somewhere else in another month is worth something, just not the same thing as the one taken this morning. What the table is for is the shape of the gap: which kinds of case an engine answers, which it refuses, and which it never gets to.\n\n",
    );

    out.push_str("## Where each engine stands\n\n");
    out.push_str("| |");
    for t in tallies {
        out.push_str(&format!(" {} |", t.engine));
    }
    out.push_str("\n|---|");
    for _ in tallies {
        out.push_str("---|");
    }
    out.push('\n');
    row(&mut out, "version", tallies, |t| t.version.clone());
    row(&mut out, "measured", tallies, |t| t.taken.clone());
    row(&mut out, "on", tallies, |t| t.host.clone());
    row(&mut out, "harness", tallies, |t| t.tool.clone());
    row(&mut out, "corpus", tallies, |t| t.selector.clone());
    row(&mut out, "cases", tallies, |t| t.cases.to_string());
    row(&mut out, "judged (pass + fail)", tallies, |t| {
        (t.pass + t.fail).to_string()
    });
    row(&mut out, "**passed**", tallies, |t| {
        format!("**{}** ({})", t.pass, pct(t.pass, t.pass + t.fail))
    });
    row(&mut out, "failed", tallies, |t| t.fail.to_string());
    row(&mut out, "skipped, cannot hold the fixture", tallies, |t| {
        t.skip.to_string()
    });
    row(&mut out, "never reached a verdict", tallies, |t| {
        t.error.to_string()
    });
    row(&mut out, "ISO features with a passing case", tallies, |t| {
        format!("{} of {}", t.features_passing, t.features_touched)
    });
    row(
        &mut out,
        "distinct GQLSTATUS values produced",
        tallies,
        |t| t.conditions_seen.to_string(),
    );
    out.push('\n');

    out.push_str("## By kind of case\n\n");
    out.push_str("Pass over judged, then the two exclusions. Read the exclusions first. An engine with a high percentage and a large skip column has answered a small and easy corner of the corpus, and the percentage on its own hides that.\n\n");
    out.push_str("| kind | engine | cases | pass | fail | skip | error | pass of judged |\n");
    out.push_str("|---|---|---|---|---|---|---|---|\n");
    for (i, kind) in KINDS.iter().enumerate() {
        for t in tallies {
            let k = &t.by_kind[i];
            out.push_str(&format!(
                "| {} | {} | {} | {} | {} | {} | {} | {} |\n",
                kind,
                t.engine,
                k[0],
                k[1],
                k[2],
                k[3],
                k[4],
                pct(k[1], k[1] + k[2])
            ));
        }
    }
    out.push('\n');

    out.push_str("## What the numbers do not say\n\n");
    out.push_str("A skip is not a pass. It means the engine declared it cannot hold the fixture the case needs, so the case never ran, and for zu almost every one of those is a limit of the loader rather than of the evaluator. The declaration behind those skips is in `conformance.toml` at the root of this repository, with a reason on every line.\n\n");
    out.push_str("The performance rows are pass and fail on a correctness check, not a speed comparison. Latency, throughput and footprint are measured per case by the harness and reported there. Nothing in this table is a timing.\n\n");
    out.push_str("An engine missing from the table is missing because nobody has taken a tally for it on a machine this repository can point at, not because it was tried and refused. Drop a `docs/conformance/<engine>.json` in and it appears in the next regeneration.\n");
    out
}

fn row(out: &mut String, label: &str, tallies: &[Tally], f: impl Fn(&Tally) -> String) {
    out.push_str(&format!("| {label} |"));
    for t in tallies {
        out.push_str(&format!(" {} |", f(t)));
    }
    out.push('\n');
}

/// `zu conformance --tally <report.json>`: distil one report.
pub(crate) fn tally_command(path: &str) -> ExitCode {
    let text = match std::fs::read_to_string(path) {
        Ok(t) => t,
        Err(e) => {
            eprintln!("zu conformance: cannot read {path}: {e}");
            return ExitCode::FAILURE;
        }
    };
    let report = match json::parse(&text) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("zu conformance: {path} is not JSON: {e}");
            return ExitCode::FAILURE;
        }
    };
    match distil(&report) {
        Ok(t) => {
            print!("{}", render_tally(&t));
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("zu conformance: {path} is not a gql-compat report: {e}");
            ExitCode::FAILURE
        }
    }
}

/// `zu conformance --regressed <report.json> <baseline.json>`: fail when
/// a kind passes fewer cases than the checked-in tally says it did.
///
/// This is the guard the per-PR job runs, and the asymmetry is on
/// purpose. A fall is a failure, because a change that makes zu answer
/// fewer cases correctly needs someone to say out loud that it was worth
/// it. A rise is not: it prints and passes, and the tally in the
/// repository is updated by a person or by the nightly, so an
/// improvement never gets to update its own scoreboard in the same
/// commit that claims it.
///
/// Only kinds the new run actually attempted are compared. The per-PR
/// job runs a subset to keep the wall clock down, and a kind it did not
/// run has zero passes for a reason that has nothing to do with the
/// engine. Counting those would make every PR fail, which is the same
/// as having no guard at all.
pub(crate) fn regressed_command(report_path: &str, baseline_path: &str) -> ExitCode {
    let fresh = match read_report(report_path) {
        Ok(t) => t,
        Err(e) => {
            eprintln!("zu conformance: {report_path}: {e}");
            return ExitCode::FAILURE;
        }
    };
    let base = match std::fs::read_to_string(baseline_path)
        .map_err(|e| e.to_string())
        .and_then(|t| load_tally(&t))
    {
        Ok(t) => t,
        Err(e) => {
            eprintln!("zu conformance: {baseline_path}: {e}");
            return ExitCode::FAILURE;
        }
    };

    let mut fell = Vec::new();
    let mut rose = Vec::new();
    let mut skipped = Vec::new();
    for (i, kind) in KINDS.iter().enumerate() {
        let now = fresh.by_kind[i];
        let was = base.by_kind[i];
        if now[0] == 0 {
            if was[0] > 0 {
                skipped.push(*kind);
            }
            continue;
        }
        if now[1] < was[1] {
            fell.push(format!(
                "{kind}: {} passing, was {} in {baseline_path}",
                now[1], was[1]
            ));
        } else if now[1] > was[1] {
            rose.push(format!("{kind}: {} passing, was {}", now[1], was[1]));
        }
        // A case that never reached a verdict is worse than one that
        // failed, because the run did not measure what it says it
        // measured. The harness treats any error as fatal on its own
        // exit status, which zu cannot use as a gate while it still has
        // errors in the baseline, so the gate is here: the count may go
        // down and may hold, and may not go up.
        if now[4] > was[4] {
            fell.push(format!(
                "{kind}: {} case(s) never reached a verdict, was {} in {baseline_path}",
                now[4], was[4]
            ));
        }
    }

    if !skipped.is_empty() {
        // Said out loud rather than left implicit. A guard that quietly
        // checks two kinds out of five reads in a green tick exactly
        // like one that checked all of them.
        println!(
            "zu conformance: not compared, this run had no cases of that kind: {}",
            skipped.join(", ")
        );
    }
    for r in &rose {
        println!("zu conformance: up, {r}");
    }
    if fell.is_empty() {
        println!("zu conformance: nothing regressed against {baseline_path}");
        if !rose.is_empty() {
            println!(
                "zu conformance: {} kind(s) improved; regenerate the tally with `zu conformance --tally` when you are ready to publish it",
                rose.len()
            );
        }
        return ExitCode::SUCCESS;
    }
    eprintln!(
        "zu conformance: {} regression(s) against the baseline:",
        fell.len()
    );
    for f in &fell {
        eprintln!("  {f}");
    }
    eprintln!(
        "zu conformance: if the fall is intended, say why in the PR and update {baseline_path}"
    );
    ExitCode::FAILURE
}

fn read_report(path: &str) -> Result<Tally, String> {
    let text = std::fs::read_to_string(path).map_err(|e| e.to_string())?;
    let report = json::parse(&text)?;
    distil(&report)
}

/// `zu conformance --scoreboard <tally.json>...`: render the page.
///
/// The engines come out in the order given so the caller decides which
/// column is first, and the drift test passes them sorted by filename
/// so the checked-in page does not depend on how a shell expanded a
/// glob.
pub(crate) fn scoreboard_command(paths: &[String]) -> ExitCode {
    let mut tallies = Vec::with_capacity(paths.len());
    for p in paths {
        let text = match std::fs::read_to_string(p) {
            Ok(t) => t,
            Err(e) => {
                eprintln!("zu conformance: cannot read {p}: {e}");
                return ExitCode::FAILURE;
            }
        };
        match load_tally(&text) {
            Ok(t) => tallies.push(t),
            Err(e) => {
                eprintln!("zu conformance: {p} is not a tally: {e}");
                return ExitCode::FAILURE;
            }
        }
    }
    print!("{}", render_scoreboard(&tallies));
    ExitCode::SUCCESS
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The smallest report that exercises every field the tally reads.
    const REPORT: &str = r#"{
      "tool": "gql-compat devel",
      "generated": "2026-08-13T21:59:57.275+07:00",
      "engine": {"adapter": "zu", "version": "zu 0.0.1"},
      "host": {"os": "darwin", "arch": "arm64", "cpu_model": "Apple M4"},
      "run": {"selector": "the whole corpus apart from its large fixtures"},
      "totals": {"cases": 6, "pass": 2, "fail": 1, "skip": 2, "error": 1,
        "by_kind": {
          "mandatory": {"cases": 2, "pass": 1, "fail": 1, "skip": 0, "error": 0},
          "condition": {"cases": 2, "pass": 1, "fail": 0, "skip": 1, "error": 0},
          "optional": {"cases": 2, "pass": 0, "fail": 0, "skip": 1, "error": 1}}},
      "coverage": {"features": {
        "G004": {"cases": 1, "pass": 1, "fail": 0},
        "G010": {"cases": 1, "pass": 0, "fail": 1}}},
      "cases": [
        {"id": "a", "got_gqlstatus": "22G03"},
        {"id": "b", "got_gqlstatus": "22G03"},
        {"id": "c", "got_gqlstatus": "42001"},
        {"id": "d", "got_gqlstatus": ""},
        {"id": "e"}]
    }"#;

    fn sample() -> Tally {
        distil(&json::parse(REPORT).expect("the sample parses")).expect("the sample distils")
    }

    #[test]
    fn a_tally_keeps_the_counts_and_drops_the_clock() {
        let t = sample();
        assert_eq!(t.engine, "zu");
        assert_eq!((t.cases, t.pass, t.fail, t.skip, t.error), (6, 2, 1, 2, 1));
        // Date only, no time. A checked-in file that changes because the
        // run started at a different minute is a file people stop reading.
        assert_eq!(t.taken, "2026-08-13");
        assert!(!t.taken.contains(':'), "the tally kept a clock time");
        assert_eq!(t.host, "darwin arm64, Apple M4");
    }

    #[test]
    fn a_kind_the_report_never_mentions_counts_as_zero_not_as_missing() {
        // The sample has no grammar or performance cases. Those rows
        // still have to appear, or a run that happened to skip a kind
        // would silently shorten the table.
        let t = sample();
        assert_eq!(t.by_kind.len(), KINDS.len());
        let grammar = KINDS.iter().position(|k| *k == "grammar").expect("grammar");
        assert_eq!(t.by_kind[grammar], [0, 0, 0, 0, 0]);
        let mandatory = KINDS.iter().position(|k| *k == "mandatory").expect("m");
        assert_eq!(t.by_kind[mandatory], [2, 1, 1, 0, 0]);
    }

    #[test]
    fn a_feature_counts_as_reached_only_when_a_case_for_it_passed() {
        let t = sample();
        assert_eq!(t.features_touched, 2);
        assert_eq!(t.features_passing, 1, "a failing feature was counted");
    }

    #[test]
    fn codes_are_counted_distinct_and_a_blank_is_not_a_code() {
        // Five cases, three with a code, one of them repeated, one blank
        // and one absent. The answer is two.
        let t = sample();
        assert_eq!(t.conditions_seen, 2);
    }

    #[test]
    fn a_tally_survives_a_round_trip() {
        // The checked-in file is read back by the scoreboard, so a field
        // that renders but does not load would show up as "unknown" in
        // the doc and nowhere else.
        let before = sample();
        let after = load_tally(&render_tally(&before)).expect("reload");
        assert_eq!(after.engine, before.engine);
        assert_eq!(after.version, before.version);
        assert_eq!(after.host, before.host);
        assert_eq!(after.taken, before.taken);
        assert_eq!(after.selector, before.selector);
        assert_eq!(after.cases, before.cases);
        assert_eq!(after.pass, before.pass);
        assert_eq!(after.by_kind, before.by_kind);
        assert_eq!(after.features_passing, before.features_passing);
        assert_eq!(after.conditions_seen, before.conditions_seen);
    }

    #[test]
    fn the_percentage_is_over_judged_cases_and_says_so_when_there_are_none() {
        // 2 passed, 1 failed, 2 skipped, 1 errored. Over judged that is
        // 66.7%. Over cases it would be 33.3%, and picking the larger
        // number while calling it the same thing is the specific
        // dishonesty this test exists to prevent.
        assert_eq!(pct(2, 3), "66.7%");
        assert_eq!(pct(1, 3), "33.3%");
        assert_eq!(pct(0, 5), "0.0%");
        assert_eq!(pct(5, 5), "100.0%");
        assert_eq!(pct(0, 0), "n/a");
        // Rounds half up rather than truncating, so 1 of 8 is 12.5 and
        // not 12.4.
        assert_eq!(pct(1, 8), "12.5%");
    }

    #[test]
    fn the_scoreboard_names_every_engine_and_every_kind() {
        let mut second = sample();
        second.engine = "ladybug".to_string();
        second.pass = 72;
        let page = render_scoreboard(&[sample(), second]);
        assert!(page.contains("| zu |") || page.contains("zu | "), "{page}");
        assert!(page.contains("ladybug"), "{page}");
        for kind in KINDS {
            assert!(page.contains(kind), "the {kind} row is missing");
        }
        // The two exclusions have to be on the page in words, not just
        // as columns. A reader who takes the headline and stops should
        // still have been told what it leaves out.
        assert!(page.contains("A skip is not a pass"));
    }

    #[test]
    fn a_scoreboard_of_nothing_is_still_a_page() {
        // The glob can legitimately match nothing on a fresh checkout,
        // and a panic there would be a worse failure than an empty
        // table with the explanation still attached.
        let page = render_scoreboard(&[]);
        assert!(page.contains("# GQL conformance"));
        assert!(page.contains("Drop a `docs/conformance/"));
    }
}
