//! zu's Clause 24 conformance statement, rendered from a measured run
//! (Spec/2064g/gql/plan/08 §6).
//!
//! ISO/IEC 39075:2024 Clause 24 defines the form of a conformance claim
//! and nothing else. It does not define a test suite, it does not name a
//! body that could adjudicate a claim, and there is no GQL certification
//! anywhere to hold one to. A statement written under those rules is
//! therefore worth exactly what the reader thinks of whoever wrote it,
//! which is why this one is not written by hand.
//!
//! Every count on the page comes out of a tally in `docs/conformance`,
//! and a tally is the distillation of one gql-compat run against a
//! version of zu on a named machine. Every feature code on the page is
//! there because a case citing that feature passed in that run. So the
//! claim and the evidence for it are the same object: there is no line
//! here that somebody could have written without first having run
//! something, and the command that produces the run is printed on the
//! page.
//!
//! The feature codes and their wording are the standard's and come out
//! of the published artifact mechanically, the same arrangement the
//! GQLSTATUS table and the Clause 24.5.2 register use. What is written
//! by hand in this file is the prose around the numbers, which says what
//! the numbers mean and what they do not.

mod features;

use crate::scoreboard::{KINDS, Tally};
use features::FEATURES;
use std::process::ExitCode;

/// One optional feature of ISO/IEC 39075:2024, verbatim.
pub struct Feature {
    /// The feature's code, which is the atom Clause 24.3 makes a claim
    /// out of.
    pub code: &'static str,
    /// What the standard calls it, in the standard's words.
    pub description: &'static str,
}

/// What the standard calls one feature, or its code again when the
/// artifact has never heard of it.
///
/// A code the artifact does not define cannot appear on a page rendered
/// from a corpus this repository does not own, and the test beside this
/// file says so, but the renderer still has to answer something rather
/// than stop: a statement that refused to print because one code moved
/// would be less useful than one that prints the code and lets the test
/// be the thing that fails.
fn describe(code: &str) -> &'static str {
    FEATURES
        .iter()
        .find(|f| f.code == code)
        .map(|f| f.description)
        .unwrap_or("not a feature of the published artifact")
}

/// Which family a feature code belongs to, which is its letters.
///
/// The standard groups features by prefix and the groups are what a
/// reader navigates by, so the table is broken on them rather than run
/// as two hundred undifferentiated rows.
fn family(code: &str) -> &str {
    let end = code
        .find(|c: char| c.is_ascii_digit())
        .unwrap_or(code.len());
    &code[..end]
}

/// The reason the corpus can write no portable case for a feature, said
/// in a sentence rather than in the harness's one word.
fn unwritable_reason(reason: &str) -> &'static str {
    match reason {
        "prose" => {
            "the standard defines the syntax as prose, so two conforming engines can \
             both provide it and share no spelling"
        }
        "unnameable" => {
            "the feature is reached only through a name the standard never supplies, so \
             any case for it would be testing a guess at that name"
        }
        _ => "the harness gave a reason this statement has no sentence for",
    }
}

/// Renders the statement from one engine's tally.
pub fn render(t: &Tally) -> String {
    let mut out = String::new();
    let mandatory = t.kind("mandatory");

    out.push_str("# zu's GQL conformance statement\n\n");
    out.push_str(&format!(
        "Generated by `zu conformance --statement docs/conformance/{}.json`. Do not edit by hand: a test regenerates it and fails on drift.\n\n",
        t.engine
    ));
    // The feature descriptions below are the standard's own wording,
    // copied out of the published artifact, and one of them says
    // "adjacent vertex patterns". zu writes node everywhere it writes
    // for itself, but it cannot reword a feature name it is claiming
    // conformance against, so the page names the exemption rather than
    // quietly disagreeing with the terminology table.
    out.push_str("<!-- terms: allow vertex -->\n\n");
    out.push_str(
        "ISO/IEC 39075:2024 Clause 24 says what a conformance claim has to contain and stops there. It defines no test suite, names no body that could adjudicate a claim, and there is no GQL certification programme anywhere to hold one to. Every GQL conformance statement in existence is therefore its author's own word, and this one would be too, so it is written the other way round: nothing on this page was typed by a person deciding what zu supports. Every number here is a count out of one measured run and every feature code here is on the page because a case citing that feature passed in that run. The run is named below and the command that reproduces it is at the bottom.\n\n",
    );

    out.push_str("## The run this claim is made from\n\n");
    out.push_str("| | |\n|---|---|\n");
    out.push_str(&format!("| engine | {} |\n", t.version));
    out.push_str(&format!("| measured | {} |\n", t.taken));
    out.push_str(&format!("| on | {} |\n", t.host));
    out.push_str(&format!("| harness | {} |\n", t.tool));
    out.push_str(&format!("| corpus | {} |\n", t.selector));
    out.push_str(&format!("| cases | {} |\n", t.cases));
    out.push_str(&format!("| passed | {} |\n", t.pass));
    out.push_str(&format!("| failed | {} |\n", t.fail));
    out.push_str(&format!("| skipped | {} |\n", t.skip));
    out.push_str(&format!("| never reached a verdict | {} |\n", t.error));
    out.push('\n');
    out.push_str(
        "Broken out by what each case is asking, since the five kinds ask different questions and a total over them would answer none of them. Every claim below rests on one of these rows and says which.\n\n",
    );
    out.push_str("| kind | cases | pass | fail | skip | no verdict |\n|---|---|---|---|---|---|\n");
    for kind in KINDS {
        let k = t.kind(kind);
        out.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} |\n",
            kind, k[0], k[1], k[2], k[3], k[4]
        ));
    }
    out.push('\n');
    out.push_str(
        "A performance case is graded on the answer and on a budget for the time and the memory it took to produce it, so a failure in that row can be either an answer that was wrong or a bound that was missed, and the report says which. Nothing below is claimed off a case that did not pass.\n\n",
    );

    out.push_str("## Minimum conformance, Clause 24.2\n\n");
    out.push_str(
        "Minimum conformance is all or nothing. An implementation either provides the mandatory language or it is not GQL, and no percentage means anything at this level, so the only useful thing a statement can say here is which of the two it is and what the evidence is.\n\n",
    );
    if mandatory[2] == 0 && mandatory[3] == 0 && mandatory[4] == 0 && mandatory[1] > 0 {
        out.push_str(&format!(
            "**zu claims minimum conformance.** All {} cases the corpus writes for the mandatory surface pass, none is skipped, and none failed to reach a verdict. What that is evidence of and what it is not is in the last section: the corpus is one reading of the standard's prose and nobody has adjudicated it.\n\n",
            mandatory[0]
        ));
    } else {
        out.push_str(&format!(
            "**zu does not claim minimum conformance.** Of the {} cases the corpus writes for the mandatory surface, {} pass, {} fail, {} are skipped and {} never reached a verdict. A claim is not made until that row is clean.\n\n",
            mandatory[0], mandatory[1], mandatory[2], mandatory[3], mandatory[4]
        ));
    }

    out.push_str("## Optional features, Clause 24.3\n\n");
    out.push_str(
        "Clause 24.3 makes every optional feature a separate claim, addressed by its code, which is why this is a list of codes and not a percentage. A feature is on this list when a case citing it passed in the run above, and it is on no other grounds: an intention to support one, or an implementation of one no case reaches, does not appear here.\n\n",
    );
    out.push_str(&format!(
        "**zu claims {} of the {} optional features the standard defines.**\n\n",
        t.features_claimed.len(),
        t.features_total
    ));

    let mut fam = "";
    for code in &t.features_claimed {
        if family(code) != fam {
            if !fam.is_empty() {
                out.push('\n');
            }
            fam = family(code);
            out.push_str(&format!(
                "### Family {fam}\n\n| feature | what the standard calls it |\n|---|---|\n"
            ));
        }
        out.push_str(&format!("| {} | {} |\n", code, describe(code)));
    }
    out.push('\n');

    if !t.features_unwritable.is_empty() {
        out.push_str("### The features this claim says nothing about\n\n");
        out.push_str(&format!(
            "{} of the standard's {} features have no case in the corpus, and they are absent from the claim above rather than denied by it. In each of them the standard leaves the spelling to the implementation, so a portable case cannot exist and no run could produce evidence either way.\n\n",
            t.features_unwritable.len(),
            t.features_total
        ));
        out.push_str(
            "| feature | what the standard calls it | why no case exists |\n|---|---|---|\n",
        );
        for (code, reason) in &t.features_unwritable {
            out.push_str(&format!(
                "| {} | {} | {} |\n",
                code,
                describe(code),
                unwritable_reason(reason)
            ));
        }
        out.push('\n');
    }

    out.push_str("## Conditions\n\n");
    out.push_str(&format!(
        "The standard defines {} GQLSTATUS conditions and zu answers a case with the right one for {} of them. Each of the rest is named with its reason in `conformance.toml` at the root of this repository, because a condition that never fires because the engine cannot fail that way and a condition that never fires because the engine gets it wrong read identically from outside.\n\n",
        t.conditions_total, t.conditions_passing
    ));
    // The two kinds of unpassed condition are separated here rather than
    // left as one remainder, because the remainder is the number a reader
    // is entitled to be suspicious of and the two halves answer that
    // suspicion in different ways.
    if t.conditions_unreachable > 0 || t.conditions_measured > 0 {
        out.push_str(&format!(
            "Of the {} that have no passing case, {} cannot be raised by anything zu is sent: the standard defines them for an engine that lacks a feature zu has, so the only way to make one fire would be to take the feature out, which would be a worse engine with a better number. The other {} are limits the standard leaves to the implementation. A case asked for a size and zu simply took it, so nothing was refused and there is no verdict, but the answer is still a measurement: zu's limit on that item is at least what was asked.\n\n",
            t.conditions_total - t.conditions_passing,
            t.conditions_unreachable,
            t.conditions_measured
        ));
    }
    out.push_str(&format!(
        "Across the whole run zu produced {} distinct GQLSTATUS codes, counted off the replies rather than off a summary, since a code the engine emitted once is the evidence that the machinery behind it works at all.\n\n",
        t.conditions_seen
    ));

    out.push_str("## What the standard leaves open, Clause 24.5.2\n\n");
    out.push_str(
        "The other half of what Clause 24 asks for is not what zu supports but what zu chose where the standard declined to choose. That is 117 implementation-defined items and 20 implementation-dependent ones, and zu's answer to every one of them is in `docs/gql-implementation-defined.md`, generated by `zu conformance --implementation-defined`. Two of the answers are absences, stated as absences, and they are the reason two of the unreachable conditions above are unreachable.\n\n",
    );

    out.push_str("## Extensions and options, Clause 24.5.3\n\n");
    out.push_str(
        "zu adds no syntax to GQL. Every statement it accepts is a statement of the standard's grammar, and a statement outside that grammar is refused with a syntax error rather than given a meaning of zu's own, which is what makes the grammar cases above worth anything. There is no vendor prefix, no pragma and no dialect switch, so there is nothing here for a portable query to avoid.\n\n",
    );
    out.push_str(
        "What zu adds is outside the language: a command line, a JSON line protocol on a session, an Arrow encoding of a result, a loader that reads a SQLite database in zu's schema, and the conformance reporting this page is part of. None of those is reachable from a GQL-program and none changes what one means.\n\n",
    );

    out.push_str("## How far the evidence reaches\n\n");
    out.push_str(&format!(
        "The corpus behind this claim cites the standard mechanically, and the two numbers that say how much of the standard it has reached at all are these: {} of the {} normative subclauses have a passing case, and {} of the {} productions of the published grammar do. Those are properties of the corpus and not of zu. A subclause with no case is one nobody has written a case for; it is not one zu failed, and it is not one zu passed either.\n\n",
        t.subclauses_passing, t.subclauses_total, t.productions_passing, t.productions_total
    ));
    // Neither difference above need be a gap, and saying which part of it
    // is takes the rest of the arithmetic. Without it a reader has to
    // assume the whole remainder is untested ground, which is the
    // opposite of what the harness checked.
    out.push_str(&format!(
        "Not all of either difference is untested ground. {} of the productions are rules the harness registers as uncitable, each because the rule spells the name of a catalog object no GQL statement creates or hangs off a feature the standard leaves unspelled. On the subclause side {} are registered the same way and {} are clause headings that no case names directly and a passing case reaches through what they hold, since a heading specifies nothing on its own. The reasons are checked against the standard's own text by the harness rather than asserted here.\n\n",
        t.productions_registered, t.subclauses_registered, t.subclauses_beneath
    ));
    let open_productions = t
        .productions_total
        .saturating_sub(t.productions_passing)
        .saturating_sub(t.productions_registered);
    let open_subclauses = t
        .subclauses_total
        .saturating_sub(t.subclauses_passing)
        .saturating_sub(t.subclauses_registered)
        .saturating_sub(t.subclauses_beneath);
    if open_productions == 0 && open_subclauses == 0 {
        out.push_str(
            "Those account for both remainders exactly, so on this run there is no production and no subclause of the standard that the corpus has neither reached nor given a reason for. That is a statement about the corpus rather than about zu, and it is the one the corpus was built to be able to make.\n\n",
        );
    } else {
        out.push_str(&format!(
            "What is left after those is {} productions and {} subclauses that the corpus has neither reached nor given a reason for. Those are the ones still to write cases for, and they are printed here rather than folded into a remainder because a number nobody has accounted for is the only kind worth chasing.\n\n",
            open_productions, open_subclauses
        ));
    }

    out.push_str("## What this statement is not\n\n");
    out.push_str(
        "It is not a certificate. ISO publishes no conformance test for GQL, recognises none published by anybody else, and Clause 24 does not contemplate one, so nobody is in a position to hand an engine a pass. The corpus behind these numbers is one careful reading of the standard's prose into executable cases, every case citing the subclause it came from, and a second competent reader could write a case that cites the same subclause and disagrees with it. There is no mechanism anywhere for settling that.\n\n",
    );
    out.push_str(
        "It is also a claim about one build on one machine on one day. Both are printed above for that reason.\n\n",
    );

    out.push_str("## Reproducing it\n\n");
    out.push_str(
        "The full report behind the tally is a megabyte of per-case timings, host readings and a wall clock, none of it the same twice, so it is not checked in anywhere. What is checked in is the tally this page is rendered from, and the four commands that regenerate the whole chain from an engine binary:\n\n",
    );
    out.push_str("```\n");
    out.push_str("cargo build --release -p zu-cli\n");
    out.push_str(
        "gql-compat run -adapter zu -binary target/release/zu -fail-on none -out reports/zu\n",
    );
    out.push_str(&format!(
        "zu conformance --tally reports/zu/zu.json > docs/conformance/{}.json\n",
        t.engine
    ));
    out.push_str(&format!(
        "zu conformance --statement docs/conformance/{}.json > docs/gql-conformance-statement.md\n",
        t.engine
    ));
    out.push_str("```\n\n");
    // The one claim above that no engine run can check. Everything else
    // on this page is a count out of a report; the registers are an
    // argument about the standard's text, and an argument needs a command
    // of its own or it is back to being somebody's word.
    out.push_str(
        "The registered items are the one part of this page that no engine run can check, since they are claims about the standard's own text rather than about zu. The command that checks them takes no engine at all:\n\n",
    );
    out.push_str("```\n");
    out.push_str("gql-compat validate\n");
    out.push_str("```\n\n");
    out.push_str(
        "It reads the corpus and the standard and re-derives the same four rows this page quotes, so the reasons behind every registered feature, rule and subclause are re-checked from the text rather than carried forward from whoever wrote them down. Its GQLSTATUS row reads 68 claimed rather than 63, because a corpus can claim a code that an engine with a given feature can never raise, and which of the two you want depends on whether you are asking about the corpus or about zu.\n\n",
    );
    out.push_str(
        "The harness is [gql-compat](https://github.com/tamnd/gql-compat), which measures other engines the same way. `docs/gql-conformance.md` is the same corpus against zu, Neo4j and Ladybug side by side, and `docs/gql-performance.md` is what those same answers cost.\n",
    );
    out
}

/// `zu conformance --statement <tally.json>`: render the claim.
pub(crate) fn statement_command(path: &str) -> ExitCode {
    match crate::scoreboard::tally_from_file(path) {
        Ok(t) => {
            print!("{}", render(&t));
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("zu conformance: {e}");
            ExitCode::FAILURE
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The artifact holds the 228 features the standard defines, which is
    /// the denominator every claim on the page is read against.
    #[test]
    fn the_artifact_holds_every_feature() {
        assert_eq!(FEATURES.len(), 228);
    }

    /// No two rows of the generated table carry the same code, which is
    /// what makes `describe` a function rather than a choice.
    #[test]
    fn a_feature_code_appears_once() {
        for f in FEATURES {
            let n = FEATURES.iter().filter(|g| g.code == f.code).count();
            assert_eq!(n, 1, "feature {} appears {n} times", f.code);
        }
    }

    /// A code splits into letters and digits, which is what the family
    /// headings are made of. A code that did not would land every
    /// feature under one heading, silently.
    #[test]
    fn every_code_is_letters_then_digits() {
        for f in FEATURES {
            let fam = family(f.code);
            assert!(!fam.is_empty(), "feature {} has no family", f.code);
            assert!(
                fam.chars().all(|c| c.is_ascii_uppercase()),
                "family of {} is not letters",
                f.code
            );
            assert!(
                f.code[fam.len()..].chars().all(|c| c.is_ascii_digit()),
                "feature {} is not letters then digits",
                f.code
            );
        }
    }

    /// The two reasons the harness gives for a feature no case can be
    /// written for both have a sentence here. A third reason arriving
    /// upstream would otherwise be published as a shrug.
    #[test]
    fn every_reason_the_harness_gives_has_a_sentence() {
        for reason in ["prose", "unnameable"] {
            assert!(
                !unwritable_reason(reason).starts_with("the harness gave"),
                "no sentence for the reason {reason}"
            );
        }
    }
}
