//! What the committed `docs/api/model.json` has to be true of.
//!
//! The file in the tree is what every downstream reader consumes: the
//! reference pages, the SDK feature matrix, `zu.h`, the completeness
//! check. Regenerating it needs nightly, so CI's `cargo xtask model
//! --check` runs on one pinned job and this runs everywhere, on the
//! bytes as committed. It is a cheap way to catch a model that was
//! generated against a half-built workspace and committed anyway.

use zu_json::{Json, parse};

fn model() -> Json {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../docs/api/model.json");
    let text = std::fs::read_to_string(path).expect("docs/api/model.json is in the tree");
    parse(&text).expect("docs/api/model.json is JSON")
}

fn entities(model: &Json) -> &[Json] {
    model
        .get("entities")
        .and_then(Json::as_arr)
        .expect("the model has an entities array")
}

#[test]
fn the_committed_model_is_the_schema_the_readers_were_promised() {
    let model = model();
    assert_eq!(
        model.get("schema").and_then(Json::as_i64),
        Some(xtask::model::SCHEMA)
    );
    assert_eq!(
        model.get("rustdoc_format_version").and_then(Json::as_u64),
        Some(xtask::rustdoc::FORMAT_VERSION),
        "the model was generated by a rustdoc this generator no longer reads"
    );
    assert!(model.get("crate").and_then(Json::as_str).is_some());
    assert!(model.get("version").and_then(Json::as_str).is_some());
}

#[test]
fn every_public_name_resolved_to_something() {
    // `unresolved` means a re-export pointed at a crate the generator
    // was not handed. Downstream that is a binding with a name and no
    // type behind it, which is worse than a name that is simply absent.
    let model = model();
    let stranded: Vec<&str> = entities(&model)
        .iter()
        .filter(|e| e.get("kind").and_then(Json::as_str) == Some("unresolved"))
        .filter_map(|e| e.get("id").and_then(Json::as_str))
        .collect();
    assert!(
        stranded.is_empty(),
        "unresolved entities, so REEXPORTED in crates/xtask/src/main.rs is missing a crate: {stranded:?}"
    );
}

#[test]
fn no_signature_gave_up_halfway() {
    // The renderer writes `?tag` for a rustdoc type it does not know,
    // rather than dropping it, so a format change shows up as a diff
    // instead of as a quietly wrong signature. None may survive into
    // the committed file.
    let model = model();
    let unrendered: Vec<(&str, &str)> = entities(&model)
        .iter()
        .filter_map(|e| {
            let sig = e.get("signature").and_then(Json::as_str)?;
            sig.contains('?')
                .then(|| (e.get("id").and_then(Json::as_str).unwrap_or("?"), sig))
        })
        .collect();
    assert!(
        unrendered.is_empty(),
        "signatures rustdoc used a tag we do not render: {unrendered:?}"
    );
}

#[test]
fn no_signature_says_crate_to_a_reader_outside_the_crate() {
    // rustdoc renders a path the way the source wrote it. `crate::Foo`
    // is correct inside the defining crate and names nothing anywhere
    // a binding generator will read it.
    let model = model();
    let inward: Vec<&str> = entities(&model)
        .iter()
        .filter(|e| {
            e.get("signature")
                .and_then(Json::as_str)
                .is_some_and(|s| s.contains("crate::"))
        })
        .filter_map(|e| e.get("id").and_then(Json::as_str))
        .collect();
    assert!(
        inward.is_empty(),
        "signatures still say crate::: {inward:?}"
    );
}

#[test]
fn everything_that_should_carry_a_type_carries_one() {
    // A field, method, constant, alias, or variant with a name and no
    // signature is a row a header generator cannot emit, and it fails
    // there rather than here unless this catches it. Structs, enums,
    // traits, and modules are the kinds that legitimately have none:
    // their shape is their members.
    let model = model();
    let bare: Vec<(&str, &str)> = entities(&model)
        .iter()
        .filter(|e| {
            matches!(
                e.get("kind").and_then(Json::as_str),
                Some(
                    "field"
                        | "method"
                        | "function"
                        | "constant"
                        | "type-alias"
                        | "variant"
                        | "assoc-const"
                        | "assoc-type"
                )
            ) && e.get("signature").is_none()
        })
        .filter_map(|e| {
            Some((
                e.get("id").and_then(Json::as_str)?,
                e.get("kind").and_then(Json::as_str)?,
            ))
        })
        .collect();
    assert!(bare.is_empty(), "entities with no signature: {bare:?}");
}

#[test]
fn identifiers_are_unique_and_sorted() {
    // Sorted because a diff of this file should show what changed in
    // the API and nothing else; unique because the id is the key every
    // downstream map is built on.
    let model = model();
    let ids: Vec<&str> = entities(&model)
        .iter()
        .filter_map(|e| e.get("id").and_then(Json::as_str))
        .collect();
    assert_eq!(ids.len(), entities(&model).len(), "an entity has no id");
    for pair in ids.windows(2) {
        assert!(pair[0] < pair[1], "out of order or duplicated: {pair:?}");
    }
}

#[test]
fn every_member_names_a_parent_that_is_in_the_model() {
    let model = model();
    let ids: std::collections::HashSet<&str> = entities(&model)
        .iter()
        .filter_map(|e| e.get("id").and_then(Json::as_str))
        .collect();
    let root = model
        .get("crate")
        .and_then(Json::as_str)
        .expect("crate name");
    let orphans: Vec<(&str, &str)> = entities(&model)
        .iter()
        .filter_map(|e| {
            let of = e.get("of").and_then(Json::as_str)?;
            (!ids.contains(of) && of != root)
                .then(|| (e.get("id").and_then(Json::as_str).unwrap_or("?"), of))
        })
        .collect();
    assert!(
        orphans.is_empty(),
        "entities whose owner is not in the model: {orphans:?}"
    );
}

#[test]
fn the_surface_still_has_the_pieces_a_binding_needs() {
    // A generator that silently produced an empty model would pass
    // every property above. These are the names the C ABI and every
    // SDK are built out of, so their absence is the failure to catch.
    let model = model();
    let ids: std::collections::HashSet<&str> = entities(&model)
        .iter()
        .filter_map(|e| e.get("id").and_then(Json::as_str))
        .collect();
    for want in [
        "zu::session::Session",
        "zu::session::Session::open",
        "zu::GqlStatus",
        "zu::DiagnosticRecord",
        "zu::GraphStore",
    ] {
        assert!(ids.contains(want), "{want} is missing from the model");
    }
    assert!(
        entities(&model).len() > 400,
        "only {} entities, which is not the public surface of zu",
        entities(&model).len()
    );
}
