# Generated by `cargo xtask packaging` from platforms.toml. Edit that, not this.
#
# The digests are the release's own, copied from the SHA256SUMS it
# published, so `brew install` checks exactly what the install script
# checks. A digest of sixty-four zeros is a formula rendered before the
# release it names, which fails at the checksum rather than installing
# something nobody signed off on.
class Zu < Formula
  desc "Embedded property graph database with a GQL engine"
  homepage "https://github.com/tamnd/zu"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/tamnd/zu/releases/download/v0.0.1/libzu-aarch64-apple-darwin.tar.zst"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/tamnd/zu/releases/download/v0.0.1/libzu-x86_64-apple-darwin.tar.zst"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/tamnd/zu/releases/download/v0.0.1/libzu-aarch64-unknown-linux-gnu.tar.zst"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/tamnd/zu/releases/download/v0.0.1/libzu-x86_64-unknown-linux-gnu.tar.zst"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "bin/zu"
    lib.install Dir["lib/*"]
    include.install Dir["include/*"]
    prefix.install "LICENSE"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zu version")
    assert_match "usage: zu <command>", shell_output("#{bin}/zu --help")
  end
end
