[package]
name = "zu-query"
description = "Parser, planner, and factorized vectorized executor for zu"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
crossbeam-deque = "0.8.7"
zu-common.workspace = true
zu-storage.workspace = true
zu-vector.workspace = true

[[bench]]
name = "columnar"
harness = false

[[bench]]
name = "kernels"
harness = false

[lints]
workspace = true
